name: test_auth
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  google_sign_in: ^7.2.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.5
  http: ^1.6.0
  url_launcher: ^6.3.2
  flutter_facebook_auth: ^7.2.0
  dio: ^5.11.0
  flutter_secure_storage: ^10.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_info_plus: ^13.2.0
  package_info_plus: ^10.2.1
  uuid: ^4.6.0
  flutter_alice: ^2.0.1
  overlay_support: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

 
