# Generated by Django 5.2.17 on 2026-09-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=16)),
                ('destination', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['destination', 'channel', 'is_used'], name='otp_auth_ot_destina_6f444f_idx')],
            },
        ),
    ]
